env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_MENU_PREFIX,arch-

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, Escape, exec, killall waybar || waybar

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod, right, workspace, e+1
bind = $mainMod, left, workspace, e-1
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2

input {
    kb_layout = br
    kb_variant = abnt2,
}

exec-once = waybar
exec-once = nwg-dock-hyprland -r -p bottom -a center -i 24 -x
exec-once = swaybg -i ~/.wallpaper/wallpaper3.png -m fi
exec-once = swaync
